---
- name: copy ssh config
  copy:
    src: ssh/config
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
    backup: yes
